### ISSUE TITLE
expose compiler version used to build JLL somewhere

### ISSUE THREAD

**Issue by Crghilardi** [JuliaPackaging/BinaryBuilder.jl#1110]
I have asked this on Slack previously, but thought it might be worth adding here as well.

Info on which version of compiler was used to make a `JLL` is only available in the Azure logs or at the bottom of a `build_tarballs.jl`. It would be helpful if that was "digestible" in some format and could be used to check dependencies ahead of time vs debugging log files.

I am imagining the wizard return a prompt something like:
`Dependency Foo in [Foo, Bar, Baz] lists preferred_gcc_version as 7, we recommend using that to avoid compile issues`. 

I don't know if this would work as a wizard or README thing? Would this maybe work as another `fancytoy` that just takes in a list of `JLL` names and scrapes the README to compare them or something? min_common_compiler("Foo_jll", "Bar_jll", "Baz_jll")? I suppose this is all GCC specific as well, I don't think Clang needs to do this?

**Comment by giordano** [comment]
It's at the top of the build log

**Comment by giordano** [comment]
Oh, sorry, now I see what you mean.

One thing to keep in mind is that the "preferred version" is not necessarily the version actually used, that depends on a lot of constraints for each platform (e.g., for aarch64-apple-darwin we have *only* GCC 11, for C++11 string ABI we can use only GCC >= 5, for libgfortran 3 we can use 4 <= GCC <= 6, for libgfortran 4 only GCC 7, for libgfortran only GCC >= 8, there are further constraints if you ask for specific microarchitectures, etc...).

Also, it isn't always the case that you need a compiler at least as recent as the one used for the dependencies.  There are only few weird cases where this is true  (mainly related to either linker issues, or versioned symbols), so printing a warning would encourage people to always use a more recent version, which is the opposite of what we want, for compatibility.

**Comment by Crghilardi** [comment]
Yes, I think I am basically referring to a convenience check for the bullet [from the Troubleshooting guide?](https://docs.binarybuilder.org/stable/troubleshooting/#Building-with-an-old-GCC-version-a-library-that-has-dependencies-built-with-newer-GCC-versions).

I have run into this a few times now where the build fails and I check `config.log` and it says something like `GLIBCXX@...` (can't remember exact message). 

I think I usually run into this with things using `GEOS` or `GDAL` as dependencies since they are "pinned" to use `v6`. Adding a `preferred_gcc_version` flag usually fixes everything, but I thought it would be nice to be able to warn things like that for a user ahead of time somehow if possible.

**Comment by giordano** [comment]
I feel like this is something that you have to try and get the error, in order to know that you have to bump the required version of GCC, not something we should suggest beforehand.  The suggestion could come from the compiler wrapper, when catching the error.  This would be along the same line as #826 and #930

**Comment by Crghilardi** [comment]
Not wanting to proactively suggest higher compiler versions make sense, I was not considering that previously. 

I don't know if capturing `stderr` would be useful in detecting what I am trying to describe?
Each time I have run into this has been the same general set up, where a library using `./configure` will fail on some check and only once I get into the `config.log`, I see the actual error messages point to GLIBCXX/ symbol weirdness. 

There may not be a good answer for this or be a dependency specific quirk, I have just ran into it enough times to assume a pattern and was hoping to automate around it a bit if possible.

**Comment by Crghilardi** [comment]
I went back and tried to find a concrete example and the most recent one might be [librttopo](https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/librttopo/build_tarballs.jl). When I originally submitted it, I needed gcc6 otherwise it would fail and complain, but I just pulled it down again and tried without a `preferred_gcc_version` on `x86_64-linux-gnu` and it worked fine. Same with [libspatialite](https://github.com/JuliaPackaging/Yggdrasil/tree/master/L/libspatialite), everything is working fine now without a preferred_gcc_version, so  ¯\\_(ツ)_/¯

**Comment by giordano** [comment]
> I don't know if capturing stderr would be useful in detecting what I am trying to describe?

Yes, that's basically what #826 and #930 would do as well, that's why I think this is just one more thing that could be incorporated in a smart compiler wrapper.

Although the idea is cool, I personally never went on to do that because

1. different compilers and compiler versions can have very different messages, catching all possible errors can be extremely tricky
2. also, we may want to catch a wide variety of errors (we already have 3 tickets with different ideas about this), that'd be even more complicated
3. related to the points above, all this extra logic would likely cause a sensible slowdown during compilation.  However we dynamically generate the wrappers, so we could have an option to enable/disable these hints, which are maybe enabled by default in the wizard and off by default when running the `build_tarballs.jl` script.

**Comment by giordano** [comment]
I have suggested adding this in #639, I'm going to close this ticket.
