### ISSUE TITLE
BinaryBuilder does not cross-compile for Apple ARM64 macOS systems

### ISSUE THREAD

**Issue by truedichotomy** [JuliaPackaging/BinaryBuilder.jl#1135]
The current version of BinaryBuilder (running on Julia 1.6) does not have the option/ability to compile for ARM64 macOS systems. I think that's preventing a lot of packages from working natively on M1 Macs as they depend on the platform specific JLLs in Yggdrasil.

**Comment by jeremiahpslewis** [comment]
Hey! First of all, if you're looking to use Julia & Yggdrasil / BinaryBuilder with an M1 Macs, welcome, you're definitely not alone! :)

If I understand you correctly and you are looking for binaries built for Mac Apple Silicon machines, Yggdrasil & BinaryBuilder have you covered, provided you use Julia 1.6+ and the package you need has been built for experimental platforms (you can see whether this is the case in a build script, like [here](https://github.com/JuliaPackaging/Yggdrasil/blob/5d62793f6c63dc9e90827e2d7e8623ab45ce5c6e/C/cargo_license/build_tarballs.jl#L24) or check the readme of the jll you want to use for the triplet `aarch64-apple-darwin` like [here](https://github.com/JuliaBinaryWrappers/cargo_license_jll.jl).

If you want to build binaries locally, you can use the invocation documented [here](https://docs.binarybuilder.org/stable/FAQ/#Can-I-publish-a-JLL-package-locally-without-going-through-Yggdrasil?) alongside the `aarch64-apple-darwin` triplet.

This issue tracks progress in enabling Apple Silicon support in individual packages: https://github.com/JuliaPackaging/Yggdrasil/issues/2763, we're not yet at the point where all packages which *could* support apple silicon **do** support it, but there's real momentum and if there's a specific package which is already on Yggdrasil which you need for M1, I'd be happy to take a look at it!

**Comment by giordano** [comment]
Yes, it isn't clear what you're asking: `BinaryBuilder.jl` has had the ability to target `aarch64-apple-darwin` for [more than one year](https://github.com/JuliaPackaging/Yggdrasil/pull/1626), and I thought you were already aware of that since [I had already mentioned to you](https://github.com/JuliaPackaging/BinaryBuilderBase.jl/issues/170#issuecomment-985037183) this ability and [you even opened a PR](https://github.com/JuliaPackaging/Yggdrasil/pull/4013) to build HDF5 for that platform, except HDF5 can't be cross-compiled at all, but that's a totally different problem and totally unrelated to the `aarch64-apple-darwin` platform

**Comment by jeremiahpslewis** [comment]
Fedora follows the following [practices](https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/#_license_for_binary_packages):

1. "the effective license for the subpackage containing the built binary must be calculated from the individual licenses of all dependencies"
2. "the list of individual licenses and the License tag with the effective license MUST be included"

**Comment by truedichotomy** [comment]
@jeremiahpslewis, @giordano thank you for your responses. it seems that I need to manually edit the `build_tarballs.jl` to enable experimental platforms. When I ran `BinaryBuilder.run_wizard()` (trying to build https://github.com/TEOS-10/GSW-C), I didn't see the option to build for experimental platforms like `aarch64-apple-darwin`, did I miss something?

**Comment by giordano** [comment]
Ok, in the wizard it's currently not visible because it loops over `supported_platforms()`, which at the moment doesn't include `aarch64-apple-darwin`.  This platform is only in `supported_platforms(; experimental=true)`.  You can always edit the build script generated by the wizard to add the platform, or explicitly use `experimental=true`.  We'll change the default value of `experimental` soon:tm:.

**Comment by abhayap** [comment]
@jeremiahpslewis could you please take a look at adding Apple M1 support to this: https://github.com/JuliaPackaging/Yggdrasil/tree/master/L/libportaudio

**Comment by jeremiahpslewis** [comment]
@abhayap Hey! If you get a PR going, I'd be happy to take a look (can't promise results though). Are you already familiar with the Yggdrasil / BinaryBuilder ecosystem?

**Comment by abhayap** [comment]
Thanks @jeremiahpslewis! I created a PR here: https://github.com/JuliaPackaging/Yggdrasil/pull/4158. I got it compiling on AArch64 MacOS but some of the other platforms are failing. Do you know what might be happening? I'm very new to the BinaryBuilder ecosystem.

**Comment by jeremiahpslewis** [comment]
@abhayap Awesome! Looked at your PR, great to see all but one platforms build. I commented on your PR with a suggestion as I cannot edit it directly. :)
