### ISSUE TITLE
The generated build.jl uses the names libfoo and fooifier

### ISSUE THREAD

**Issue by davidanthoff** [JuliaPackaging/BinaryBuilder.jl#143]
Those should be replaced with the proper names.

**Comment by davidanthoff** [comment]
I guess the broader question is: why is ``@write_deps_file`` a macro and not just a normal function that accepts the ``products`` array?

**Comment by staticfloat** [comment]
Some discussion around this occurred on Slack, but I want to hash this out a little more.

The problem is that the user has this concept of "Products" that they want.  E.g. [IpoptBuilder](https://github.com/staticfloat/IpoptBuilder) [has a `libipopt.{so,dylib,dll}`](https://github.com/staticfloat/IpoptBuilder/blob/3fc1e8841c6d25900f8fa0a2371f2c9b07199133/build_tarballs.jl#L112) that it wants to generate.  The consuming package Ipopt.jl has [a `libipopt` variable](https://github.com/JuliaOpt/Ipopt.jl/blob/6de0898ba2797fbba6bd6cfced89a4e2154130cf/src/Ipopt.jl#L5-L10) that it wants to use in `ccall()` and such.  The `deps.jl` file is conceptually the mapping between product and variable, and we need a consistent and easy-to-use method that allows users to map between the two.

I am currently dissatisfied with the lack of integration between the various stages of building.  Right now, we run the Wizard, which generates a `build_tarball.jl`, which we then run to generate tarballs and (maybe) a `build.jl`, which we then finally run to install our products and generate a `deps.jl`.  This whole chain of events is necessary because we have four distinct stages; build design (work done in Wizard, result baked into `build_tarballs.jl`), tarball building (work done in `build_tarballs.jl`, result baked into `build.jl`), tarball installation (work done in `build.jl`, result baked into `deps.jl`) and binary loading (work done in `deps.jl`, result used by consuming package).

Communicating information from one stage to another is a little tricky; right now we're mostly doing this by copy-pasting scripts/templates from one file to another.  That's fine, but we should be generating files with as much detail as we possibly can, and also absorb as much complexity into things like `autobuild()` as we possibly can.  I think we're doing an okay job here, but there are a few things I'm really dissatisfied with, and anytime `products` appears that dissatisfaction rears its ugly head at me.

I would like for the definition of `products` to be the same across all stages of the build process.  For this to be so, we need to collect a little more information from the user than we do now; in essence, we need to ask the user what variable name they would like associated with each build product.  E.g.: at Wizard time, right now we ask the user what products they would like to define as "needed"; if we collect a variable name from them at that point as well, we can carry that information around with us all the time, and make things consistent across every stage.

Concretely this means we change:

* Wizard build stage; we ask for a (valid) variable name at product-choosing time.

* `build_tarballs.jl` stage; we provide products in a manner such as:
```julia
products(prefix) = [
    LibraryProduct(prefix, "libreadstat", "libreadstat")
]
```

* `build.jl` stage; we provide products in a manner such as:
```
products = [
    LibraryProduct(prefix, "libreadstat", "libreadstat")
]
```

We also do not need to use a `@write_deps_file` macro, we can instead just pass `products` to a function which can get variable names from the Product objects themselves.

* `deps.jl` stage; nothing changes.  It gets generated same as always.

**Comment by davidanthoff** [comment]
That all sounds exactly right!
