### ISSUE TITLE
PPC64 Triple mismatch

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryBuilder.jl#21]
After upgrading BinaryProvider building for ppc64 fails. The triple calls this `ppc64le`, but the compiler toolchain is at `powerpc64le-linux-gnu`.

**Comment by ararslan** [comment]
Probably my bad. I can submit a fix to BinaryProvider.

**Comment by Keno** [comment]
Either fix it there, or change the triple on the compiler toolchain. cc @staticfloat

**Comment by ararslan** [comment]
Probably easier to fix it in BinaryProvider. In talking with Elliot, we decided to normalize `ppc64le` and `powerpc64le` to the same thing internally for the `Linux` type. I chose ppc because it's shorter without thinking about the name of the toolchain. Anyway, I have a PR for that up in BinaryProvider now.
