### ISSUE TITLE
Support older glibcxx versions on Linux?

### ISSUE THREAD

**Issue by stevengj** [JuliaPackaging/BinaryBuilder.jl#230]
See JuliaInterop/ZMQ.jl#176 — the BinaryBuilder packages are failing on CentOS 7 because it depends on too new a libstdc++.

Should there be an older build target for this, or just default to an older libstdc++?   Is CentOS 7 a supported Julia platform?

**Comment by stevengj** [comment]
See also https://stackoverflow.com/questions/44205687/glibcxx-3-4-21-not-found-on-centos-7 — it looks like the library might be there on CentOS 7, but there is a problem with the paths.

**Comment by Keno** [comment]
So the assumption here is that the libstdc++ used is the one that ships with binary builds of julia, since we can't really rely on the platform C++ library to have a compatible ABI. This works fine with binary builds of julia, but can cause trouble for people building from source. We may need a way for people with source builds to get a supported libstdc++.

**Comment by staticfloat** [comment]
We could do something inside `BinaryProvider` to auto-detect a too-old `libstdc++`, and warn the user, allowing them to download a `libstdc++` that gets plopped into `$JULIA_HOME/lib` or something like that.  So since `libstdc++` is backwards-compatible, the problem here is actually that the user has built Julia against a `libstdc++` that is _older_ than what we ship with julia.  Because we do not ship libc, we build against a very old `glibc`, but because we ship `libstdc++` (and use very new compilers) we ship a very new `libstdc++`.  Therefore, I think it makes sense for us to auto-detect the version of `libstdc++` and if it doesn't match what our "current `stdlibc++`" is (defined by the compiler versions we use, currently at GCC 7.3.0) we should just `BinaryProvider` ourselves a prebuilt `libstdc++`.

**Comment by jebej** [comment]
Are there any plans to create package repositories with the official Julia binaries for 1.0? It is very convenient to be able to install Julia straight from a package manager...

**Comment by ararslan** [comment]
@jebej That's unrelated to the discussion here and should be discussed elsewhere, e.g. on [Discourse](https://discourse.julialang.org). Best to keep GitHub issues on topic whenever possible.

**Comment by jebej** [comment]
I think it is somewhat on topic: the most likely reason people are using an older `libstdc++` is because they are using an unofficial Julia version from package repositories. Having official Julia package repositories then mostly negates the need for `BinaryBuilder` to support older `libstdc++`.

**Comment by staticfloat** [comment]
> Having official Julia package repositories then mostly negates the need for `BinaryBuilder` to support older `libstdc++`.

Having an official Julia package would necessitate using the compilers that the distribution uses, which would not fix this problem; we would still have the official binaries built using things like GCC 7.3.0 with its own version of `libstdc++` and the distribution sticking back on whatever older compiler it uses.  This problem is fundamental to the issue that there exist different versions of compilers that are used in different environments.

**Comment by jebej** [comment]
> Having an official Julia package would necessitate using the compilers that the distribution uses

I see, I was not aware of that. An official `flatpak` or `snap` then.

**Comment by nalimilan** [comment]
I wasn't aware of this issue. I could theoretically rebuild the Centos 7 package on the Copr to use GCC 7.2.1, which could fix the problem  (unfortunately GCC 7.3.0 isn't available via a devtoolset currently, and 7.2.1 might not be enough).

However, there seems to be a more general issue here. How will BinaryBuilder support multiple Julia versions in the future when they will have been built using different GCC versions? It seems that there will be only two choices: use the oldest GCC version which was used to build supported Julia versions (probably 1.0 and above); or automatically install a newer libstdc++.

We also need take into account the fact that official distribution packages are going to be more and more frequent once 1.0 is out, and that they will be based on the latest GCC version when the distribution was released.

**Comment by staticfloat** [comment]
@nalimilan check out https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/253 for some discussion on how I'm thinking about solving this.

**Comment by isuruf** [comment]
Any chance you can offer build tools with the oldest g++ version that julia itself can be compiled with?

**Comment by stevengj** [comment]
Hopefully closed by #253.

**Comment by stevengj** [comment]
Does not seem to have been fixed.  See JuliaInterop/ZMQ.jl#199.

**Comment by giordano** [comment]
Might have been fixed by #616 but requires a rebuild of the package

**Comment by stevengj** [comment]
I triggered a new ZMQ build in JuliaPackaging/Yggdrasil#396, so eventually that will wend its way into ZMQ.jl.

**Comment by giordano** [comment]
For the record, ZeroMQ needed to be expanded by C++ string ABIs, as it wasn't.  With #616 a warning is properly issued.

**Comment by giordano** [comment]
A new version of `ZeroMQ_jll` is in the registry

**Comment by giordano** [comment]
I think this has been fixed now, so I'm going to close this issue
