### ISSUE TITLE
exceeding Travis build-time limit

### ISSUE THREAD

**Issue by stevengj** [JuliaPackaging/BinaryBuilder.jl#233]
There are now so many BinaryBuilder platforms that my builds are exceeding Travis' 50-minute time limit: https://travis-ci.org/JuliaInterop/ZMQBuilder/builds/372036524 (`The job exceeded the maximum time limit for jobs, and has been terminated.`).

What can be done about this?

**Comment by KristofferC** [comment]
Perhaps using multiple jobs like:

https://github.com/staticfloat/LLVMBuilder/blob/98449b944fe0a148812088b1f9d8042955f2849c/.travis.yml#L18-L28

**Comment by stevengj** [comment]
One annoyance with specifying TARGET manually is that then I need to keep my `.travis.yml` file in sync with `supported_platforms()`.

Maybe I can hack something together like:
```sh
# Our build takes too long for one job, so split across 4 jobs:
matrix:
    - PART=1/4
    - PART=2/4
    - PART=3/4
    - PART=4/4
```
and then just divide the `platforms` list roughly equally among 4 jobs.

**Comment by stevengj** [comment]
It looks like this should work to implement a `--part=n/m` argument:
```jl
i = Compat.findlast(x -> startswith(x, "--part="), ARGS)
if i !== nothing
    p = parse.(Int, split(ARGS[i][8:end], '/'))
    (length(p) == 2 && p[2] > 0 && 1 ≤ p[1] ≤ p[2]) || error("invalid argument ", ARGS[i])
    n = (length(platforms) + p[2]-1) ÷ p[2]
    platforms = platforms[n*(p[1]-1)+1:min(end,n*p[1])]
end
filter!(x -> !startswith(x, "--part="), ARGS)
ARGS = filter!(x -> !startswith(x, "--part="), ARGS)
```

**Comment by stevengj** [comment]
Yes, the above code seems to have worked for ZMQBuilder.  I'll make a PR to support `--part` in BinaryBuilder itself.

**Comment by staticfloat** [comment]
The problem here is that the first job generates a `build.jl`, which is then uploaded, and Travis won't overwrite it when your last build stage runs.  The logic within `build_tarballs()` disables `build.jl` generation if you've overridden the platforms (e.g. by passing in a comma-separated list of targets) so what I would do is instead of the `--part` stuff where you have `--part=1/3` and then modify `platforms`, bake the actual platforms you want built into your `.travis.yml`.

If you don't want to do this, you have further options.  You could continue with the `--part` stuff but use `--part` to generate an entry in `ARGS` so that `build_tarballs()` thinks it's received a comma-separated list of targets.  Something like `push!(newARGS, join(",", triplet.(platforms)))`.  Alternatively, you could also just delete the `build.jl` file at the end of your script in `.travis.yml`.

**Comment by stevengj** [comment]
I think what I'll do is fork BinaryBuilder temporarily to recognize `--part` and disable generation of `build.jl`.  Once that is working I will submit a PR.
