### ISSUE TITLE
Pass through /Dev/urandom

### ISSUE THREAD

**Issue by vchuravy** [JuliaPackaging/BinaryBuilder.jl#248]
When running the LLVM test in the sandbox it fails with:
> NotImplementedError: /dev/urandom (or equivalent) not found

**Comment by staticfloat** [comment]
`sandbox`-side of this will be fixed with https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/252/commits/95745571f249e0abcb52f79b88fa34081287e778.  Since the `sandbox` is bundled with the rootfs, this won't be generally available until the next rootfs release, which might be a little while coming, as I'd like to investigate https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/253 before pushing out the next rootfs.

Luckily, once https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/252/commits/e303555ff20f8ae044b7c39595fa24a11d0ca1bc lands, using new sandbox executables will be super easy.  You just `gcc -o /tmp/sandbox BinaryBuilder.jl/deps/sandbox.c`, then `BINARYBUILDER_SANDBOX_PATH=/tmp/sandbox julia` and go about your business as usual, reaping the rewards of the fresh `sandbox` immediately.

**Comment by KristofferC** [comment]
Can be closed by https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/252 I think.
