### ISSUE TITLE
No version information available for `/usr/lib/libstdc++` within sandbox

### ISSUE THREAD

**Issue by vchuravy** [JuliaPackaging/BinaryBuilder.jl#254]
When running a binary that was built with BinaryBuilder withhin the sandbox I see the following message:

```
/workspace/srcdir/bin/clang-tblgen: /usr/lib/libstdc++.so.6: no version information available (required by /workspace/srcdir/bin/clang-tblgen)
```

**Comment by staticfloat** [comment]
I believe this is caused by us compiling with `x86_64-linux-gnu` instead of `x86_64-linux-musl`, and since the `/usr/lib/libstdc++.so.6` file that alpine serves up doesn't have the versioning information that `clang-tblgen` expects.  I'm not sure if building `clang-tblgen` with `x86_64-linux-musl` is the right fix, but it's worth a shot.

**Comment by vchuravy** [comment]
That seems to work. The comment I found online indicated, that while running binaries compiled for glibc on musl is sometimes possible ABI compatibility is not guaranteed.

**Comment by vchuravy** [comment]
Ok I was looking at https://bugs.alpinelinux.org/issues/4903#note-1
