### ISSUE TITLE
Fastly caching is not working for our build shards

### ISSUE THREAD

**Issue by staticfloat** [JuliaPackaging/BinaryBuilder.jl#316]
We need to do something about the timeouts we're getting through Fastly.  We originally did this to take advantage of multiple POPs, but the downside is that our downloads timeout before Fastly has a chance to respond when a shard has fallen out of cache.

This may be alleviated by breaking our shards into smaller pieces (e.g. a GCC 8 x86_64-linux-gnu shard, a clang aarch64-linux-gnu shard, etc....) but I think the fundamental problem will likely continue to haunt us with anything over a few hundred MB in size.

**Comment by jpsamaroo** [comment]
Is there currently a workaround or some way to have the wizard keep on going/retry whenever a shard download times out? It's rather annoying to go through a few runs, have the whole wizard die because of a timeout, and then have the "Resume previous run" option completely forget about most of the previously-ran automated builds (it just restarts from the beginning of running all of the automated builds).

**Comment by staticfloat** [comment]
The best workaround that we have right now is to run `BinaryBuilder.download_all_shards()` first, to ensure that you have everything downloaded before even starting.  We don't (yet) have a good way of verifying that the tarball that was built previously is indeed what you want; we need to build a (`source hash` + `BB hash` => `tarball hash`) mapping system to get what you want.
