### ISSUE TITLE
Support for FreeBSD 11.2

### ISSUE THREAD

**Issue by CiaranOMara** [JuliaPackaging/BinaryBuilder.jl#359]
I'm hoping FreeBSD 11.2 can easily become a supported system. Though I must admit, I am confused as to how BinaryBuilder hangs together with Julia. But, please let me know how I can assist.

https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/39
https://github.com/JuliaLang/julia/issues/29237

**Comment by ararslan** [comment]
FreeBSD 11.2 is completely supported; one of my systems runs Julia on 11.2 with no problems. The Julia issue you filed isn't a problem, it's just reflective of the machine the binaries were built on. The Arpack issue you filed is indeed an issue with that package, not with BinaryBuilder. There's nothing actionable for this repo, since all is actually well here, so I'm going to close this. Glad to see another FreeBSD user using Julia!

**Comment by CiaranOMara** [comment]
Grand! Thank you @ararslan for the clarification.
