### ISSUE TITLE
Tarball timestamps are far in the future on MacOS

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/BinaryBuilder.jl#394]
I ran BinaryBuilder on MacOS Mojave. Things went fine until I tried to manually configure and build the package to create the build script. I received many errors from configure and make that generated files were in the past of the source code. Indeed the source code had time stamps far to the future (year 2600 or so). I check the tarball -- it is fine, and building manually or running BinaryBuilder on Linux works fine.

I tried using `touch` on the source tree as a work-around, but this didn't help. Apparently something is very wrong either with the system clock in the build environment, or with the file system's metadata.

**Comment by staticfloat** [comment]
This is most likely related to the filesystem issues we have with qemu (related: https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/318).

You can try using `docker` as the backing execution engine for BinaryBuilder instead of qemu by [installing Docker](https://store.docker.com/editions/community/docker-ce-desktop-mac), then setting `BINARYBUILDER_RUNNER=docker`.

**Comment by staticfloat** [comment]
`docker` is the default now.
