### ISSUE TITLE
Restrictive permissions on toplevel directory

### ISSUE THREAD

**Issue by maleadt** [JuliaPackaging/BinaryBuilder.jl#447]
Installing FFTW.jl as root (e.g. creating Docker images, or deploying system-wide), permissions of deployed artifacts are wrong:

```
# rm -rf .julia
# julia -e 'using Pkg; Pkg.add("FFTW");'
# ls -la .julia/packages/FFTW/MJ7kl/deps/
total 28
drwxr-xr-x 3 root root 4096 okt  3 08:20 .
drwxr-xr-x 6 root root 4096 okt  3 08:20 ..
-r--r--r-- 1 root root 3614 okt  3 08:20 build_fftw.jl
-r--r--r-- 1 root root 1731 okt  3 08:20 build.jl
-rw-r--r-- 1 root root 2243 okt  3 08:20 build.log
-rw-r--r-- 1 root root 1190 okt  3 08:20 deps.jl
drwx------ 7 1000 1000 4096 okt  3 08:20 usr
```
It's not an issue with the artifacts, since it's only the permission of the root folder that's wrong:

```
$ tar -tvf FFTW.v3.3.9.x86_64-linux-gnu.tar.gz                                                                                                                                                                              
drwx------ sabae/sabae       0 2019-09-18 05:03 ./
drwxrwxr-x sabae/sabae       0 2019-09-18 05:03 ./logs/
-r--r--r-- sabae/sabae 1834571 2019-09-18 05:03 ./logs/FFTW.log
...
```

This also looks like a regression, as the FFTWBuilder.jl-provided tarballs don't have this issue:

```
$ tar -tvf FFTW.v3.3.9-alpha1.x86_64-linux-gnu.tar.gz                                                                                                                                                                       
drwxrwxr-x travis/travis     0 2019-07-30 16:55 ./
drwxr-xr-x travis/travis     0 2019-07-30 16:55 ./include/
-rw-r--r-- travis/travis 31394 2019-07-30 16:55 ./include/fftw3.h
```

**Comment by staticfloat** [comment]
Good catch!  Initial fix deployed in https://github.com/JuliaPackaging/BinaryBuilder.jl/commit/2b445ee81700117fc2a062b1ab48e83157639214, and a new version of FFTW with proper permissions is cooking.  This naturally affects essentially everything I have built all summer, so if there are other packages that need to be rebuilt right away, open a new issue on Yggdrasil with all the things that need to be rebuilt, and we'll get on that right away.  Otherwise, it will naturally come about as we slowly rebuild the world.

**Comment by maleadt** [comment]
Great, thanks for the quick fix!  I've deployed [a workaround](https://github.com/maleadt/julia-ngc/blob/6218428ce45166cd40e856d819abcb849c8b1c97/Dockerfile#L25-L26) for the container where I ran into this, so I probably won't need any specific rebuilds.
