### ISSUE TITLE
Provisions for installing library versions for multiple platforms

### ISSUE THREAD

**Issue by tshort** [JuliaPackaging/BinaryBuilder.jl#5]
Someday, Julia will (hopefully) be able to compile static code and be used as a cross compiler. It'd be nice for BinDeps2 to support that use case by allowing for installation of the same library for multiple platforms. The default `Pkg.build` could install the current platform, but an extra option could allow installation of multiple platforms.

Another use case for this feature might be a common package folder that is used by computers of different types. 

I think you can do this now with manual coding in `build.jl`, but it might be nice to have provisions to automate this.

**Comment by staticfloat** [comment]
A very interesting proposition.  The way I have BinDeps2 structured right now, binaries for different platforms have their target platform encoded in the filename (e.g. `libfoo.x86_64-linux-gnu.tar.gz`).  Binaries are installed to a `Prefix`, and I would argue that there's no point in mixing binaries together into the same prefix, so for a usecase like this, I would suggest the best practice would be to create `Prefix` for every architecture you're interested in, and install the binaries you want into the relevant prefix.  Because cross-compiling is something that's impossible now, and likely to be rare at best, I think keeping the basic installation elements flexible (as they are now) combined with a bit of custom tooling around BinDeps2 is the appropriate level of support for this.

**Comment by staticfloat** [comment]
This is possible now; by using the mid-level Artifacts plumbing, you can do things like pass `ensure_artifact_installed()` an explicit `platform` object to get the appropriate artifacts put on-disk.  Forcing a JLL package to think it is a different package will be considerably harder, but that is of questionable utility.
