### ISSUE TITLE
local build of `foo_jll` package

### ISSUE THREAD

**Issue by ssfrr** [JuliaPackaging/BinaryBuilder.jl#521]
I'd like to locally generate the `foo_jll` package for testing but I can't figure out if that's possible. It looks like generating the package is pretty intertwined with actually pushing it to GitHub. I tried `--deploy=ssfrr/foo_jll` but got several `404` errors. Then when I tried again I got a `422` "validation failed" error with the "already exists" code.

edit: I got around the `422` error by going into my GitHub settings and manually deleting the "BinaryBuilder.jl generated token" access token.

**Comment by fingolfin** [comment]
PR #861 takes care of this, essentially.

**Comment by staticfloat** [comment]
You should now (on the latest `master` of `BinaryBuilder.jl`) be able to specify `--deploy=local`, and it will build a JLL package in your `~/.julia/dev` directory, which you can immediately use with the artifacts constructed during your actual build.

If you are developing a C library locally and want to skip BB itself completely, you can deploy binaries to a `override` directory within the dev'ed out JLL package, and it will load those instead of the artifact libraries (you can double-check by looking at `Libdl.dllist()` after loading your JLL package).  Because it may not be immediately obvious what the layout of the `override` directory should be, you can use `dev_jll()` within your JLL package to dev it out, then copy the contents of the artifact in as an example layout.  Then you can replace the library at will, and immediately test changes locally as quickly as you can compile.
