### ISSUE TITLE
sys-root is missing `sys/fanotify.h`

### ISSUE THREAD

**Issue by vchuravy** [JuliaPackaging/BinaryBuilder.jl#573]
Seemingly a glibc or kernel header, encountered while trying to build RR

**Comment by vchuravy** [comment]
Can work around it for now, but you know programs that depends on recent kernel versions...

**Comment by staticfloat** [comment]
The linux kernel headers we're shipping are from `v4.12`, and they all contain `linux/fanotify.h`, but it looks like `glibc` 2.12.2 is too old to have the `fanotify` headers in `sys/`.

**Comment by staticfloat** [comment]
So, for instance, `ppc64le` has it because it uses a much more recent `glibc`.

**Comment by Keno** [comment]
Yeah, this is kinda by design. We could consider a way to opt into newer libc's (correspondingly limiting compatibility). In any case, rr is fixed, and we do allow use of the raw kernel headers, so I think this is a "fixed-for-this-case"/"by-design" for the moment, with the possibility of an additional future feature to allow newer libcs.
