### ISSUE TITLE
Improvements to jll readme

### ISSUE THREAD

**Issue by aviks** [JuliaPackaging/BinaryBuilder.jl#780]
* It might be useful if the README for jll packages showed the sources from which they are built.  So maybe enumerate all the files in a `FileSource`, and display the URL and SHA for git and archive sources. 

* It will also be useful if the README can display the current latest version of the package. 

* Now that there is BB documentation on how to use jll packages, maybe the _Usage_ section (with Examples_jll) might be made into a link. That will reduce a lot of duplication (and IMO resulting confusion)

**Comment by aviks** [comment]
* Another one: maybe link to the `build_tarballs.jl` in Yggdrasil that was used to build this package.

**Comment by fingolfin** [comment]
Amen to the last point! Because right now, if one stumbles over say https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl one has no good way of finding out that this comes from https://github.com/JuliaPackaging/Yggdrasil/blob/master/G/Graphviz/build_tarballs.jl -- hell, in this case, even just a link to https://github.com/JuliaPackaging/Yggdrasil/ would be massively helpful.

Of course once one has learned and internalized this link between `JuliaBinaryWrappers` repos and `JuliaPackaging/Yggdrasil` one does not need this anymore. But the first time around, this is priceless.

**Comment by aviks** [comment]
Another one: Display the list of platforms supported by this jll.

**Comment by fingolfin** [comment]
Related: issue #647

**Comment by giordano** [comment]
I implemented some of the suggestions made here in #794.

**Comment by giordano** [comment]
Ok, apart from a direct link to the builder (this isn't really trivial, but at least there is a link to Yggdrasil), I think I've actually addressed all points raised here.
